        window.RufflePlayer = window.RufflePlayer || {};
        window.RufflePlayer.config = {
            "publicPath": "https://unpkg.com/@ruffle-rs/ruffle/",
            "polyfills": false,
            "autoplay": "on",
            "unmuteOverlay": "hidden",
            "backgroundColor": "#000000",
            "warnOnUnsupportedContent": false,
            "letterbox": "on",
            "quality": "high",
            "scale": "showAll",
            "salign": "",
            "forceScale": true,
            "forceAlign": false,
            "frameRate": 60,
            "allowScriptAccess": false,
            "preferredRenderer": "canvas",
            "contextMenu": true,
            "showSwfDownload": false,
            "upgradeToHttps": false,
            "logLevel": "error",
            "base": null,
            "menu": true,
            "openUrlMode": "allow",
            "allowNetworking": "all"}